services:
    app:
        build:
            context: ./
        container_name: app
        depends_on:
            - mysql
        expose: 
            - "8080"
        volumes:
            - ./src:/src
            - /node_modules
        restart: "unless-stopped"
    mysql:
        image: mysql:8.0.4
        command: --default-authentication-plugin=mysql_native_password
        volumes: 
            - mysql:/var/lib/mysql
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        hostname: "mysql"
        ports:
            - "3306:3306"
        container_name: mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=board_db
    nginx:
            image: nginx:latest
            container_name: nginx
            ports: 
                - "80:80"
            volumes:
                - ./nginx.conf:/etc/nginx/nginx.conf
            restart: "unless-stopped"
volumes:
    mysql:
