services:
    app:
        build:
            context: ./
        expose: 
            - "8080"
        volumes:
            - ./src:/src
            - ./node_modules
        restart: "unless-stopped"
    mysql:
        image: mysql:8.0.4
        volumes: 
            - v-mysql:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
    nginx:
            image: nginx:latest
            ports: 
                - "80:80"
            volumes:
                - ./nginx.conf:/etc/nginx/nginx.conf
            restart: "unless-stopped"
        